### ISSUE TITLE
getArguments not exporting correctly

### ISSUE THREAD

**Issue by marshallswain** [feathersjs/feathers-commons#1]
This was working for me before the latest commit, but I'm getting the following error, now:

```
430[{"stack":"TypeError: undefined is not a function
    at Object.mixin.(anonymous function) (node_modules/feathers/lib/mixins/normalizer.js:11:22)
    at Object.self.(anonymous function) [as find] (node_modules/feathers/node_modules/uberproto/lib/proto.js:64:21)
    at Socket.<anonymous> (node_modules/feathers/node_modules/feathers-commons/lib/sockets/helpers.js:77:25)
    at Socket.emit (events.js:98:17)
    at Socket.onevent (node_modules/feathers/node_modules/socket.io/lib/socket.js:327:8)
    at Socket.onpacket (node_modules/feathers/node_modules/socket.io/lib/socket.js:287:12)
    at Client.ondecoded (node_modules/feathers/node_modules/socket.io/lib/client.js:193:14)
    at Decoder.Emitter.emit (node_modules/feathers/node_modules/socket.io/node_modules/socket.io-parser/node_modules/component-emitter/index.js:134:20)
    at Decoder.add (node_modules/feathers/node_modules/socket.io/node_modules/socket.io-parser/index.js:247:12)
    at Client.ondata (node_modules/feathers/node_modules/socket.io/lib/client.js:175:18)","arguments":["undefined"],"type":"called_non_callable","message":"undefined is not a function"}]
```

A console.log of the `require("./arguments")` line [here](https://github.com/feathersjs/feathers-commons/blob/master/src/commons.js#L1) is resulting in the following output:
```js
{ default: [Function: getArguments],
  converters: 
   { find: [Function: find],
     create: [Function: create],
     update: [Function],
     patch: [Function],
     get: [Function],
     remove: [Function] } }
```

Here is the compiled output for arguments.js
```js
"use strict";

var _interopRequire = function (obj) { return obj && obj.__esModule ? obj["default"] : obj; };

exports["default"] = getArguments;

var _ = _interopRequire(require("lodash"));

var getCallback = function (args) {
  return typeof _.last(args) === "function" ? _.last(args) : _.noop;
};
var getParams = function (args, position) {
  return typeof args[position] === "object" ? args[position] : {};
};

var updateOrPatch = function (name) {
  return function (args) {
    var id = args[0];
    var data = args[1];
    var callback = getCallback(args);
    var params = getParams(args, 2);

    if (typeof id === "function") {
      throw new Error("First parameter for '" + name + "' can not be a function");
    }

    if (typeof data !== "object") {
      throw new Error("No data provided for '" + name + "'");
    }

    if (args.length > 4) {
      throw new Error("Too many arguments for '" + name + "' service method");
    }

    return [id, data, params, callback];
  };
};

var getOrRemove = function (name) {
  return function (args) {
    var id = args[0];
    var params = getParams(args, 1);
    var callback = getCallback(args);

    if (args.length > 3) {
      throw new Error("Too many arguments for '" + name + "' service method");
    }

    if (id === "function") {
      throw new Error("First parameter for '" + name + "' can not be a function");
    }

    return [id, params, callback];
  };
};

var converters = exports.converters = {
  find: function find(args) {
    var callback = getCallback(args);
    var params = getParams(args, 0);

    if (args.length > 2) {
      throw new Error("Too many arguments for 'find' service method");
    }

    return [params, callback];
  },

  create: function create(args) {
    var data = args[0];
    var params = getParams(args, 1);
    var callback = getCallback(args);

    if (typeof data !== "object") {
      throw new Error("First parameter for 'create' must be an object");
    }

    if (args.length > 3) {
      throw new Error("Too many arguments for 'create' service method");
    }

    return [data, params, callback];
  },

  update: updateOrPatch("update"),

  patch: updateOrPatch("patch"),

  get: getOrRemove("get"),

  remove: getOrRemove("remove")
};

function getArguments(method, args) {
  return converters[method](args);
}

Object.defineProperty(exports, "__esModule", {
  value: true
});
```

Can we revert your last commit?  Or is there a better option?  Maybe I'm doing something wrong.

**Comment by daffl** [comment]
This was a bug that should be fixed in the latest 0.2.7. I just tried

```js
var commons = require('feathers-commons');

console.log(commons);
```

And `getArguments` is the function I'd expect. Also, I almost think you don't need to use this directly anymore because of https://github.com/feathersjs/feathers/pull/124.

**Comment by marshallswain** [comment]
Ahh... My bad.  I thought I had pulled the latest commits.  Thanks.

**Comment by marshallswain** [comment]
No wonder everything looked fine on Github.  I couldn't figure out why babel was transpiling it so weird.
